### ISSUE TITLE
Pilas Bloques en debian 8

### ISSUE THREAD

**Issue by ProfGuille** [HuayraLinux/pkg-pilas-engine-bloques#2]
Hello, I have debian jessie, I couldn't install Pilas Bloques. 
¿Anyone has a possible solution to it? Thanks.

Hola, tengo debian jessie. No pude instalar Pilas Bloques.
¿Alguien tiene alguna posible solución? Gracias

**Comment by hugoruscitti** [comment]
Hi @tarjetasprof !!!, do you have node-webkit installed in your system?
(http://devel.huayra.conectarigualdad.gob.ar/huayra/pool/non-free/n/node-webkit/)

**Comment by ProfGuille** [comment]
HI @hugoruscitti ! No I had not. I did install it and now it works.
Thank you.

**Comment by hugoruscitti** [comment]
awesome!
